/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hernandezgabrielproyecto2.interfaces;

import hernandezgabrielproyecto2.Solucion;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class Interfaz_Documentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz_Documentos.class.getName());
    static Solucion s;

    /**
     * Creates new form Interfaz_Documentos
     */
    public Interfaz_Documentos(Solucion s) {
        initComponents();
        this.s = s;
        
        this.setVisible(true);
        this.impresora.setText(s.obtenerColaImpresionTexto());
        String[] users = s.obtenerNombresUsuarios();
        this.sel_usuario.removeAllItems();
        for (String u : users) {
            this.sel_usuario.addItem(u);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sel_doc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        impresora = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sel_usuario = new javax.swing.JComboBox<>();
        titulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        doc_us = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Crear Documento");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 210, -1));

        sel_doc.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        sel_doc.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(sel_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 260, -1));

        impresora.setEditable(false);
        impresora.setColumns(20);
        impresora.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        impresora.setForeground(new java.awt.Color(0, 153, 204));
        impresora.setRows(5);
        jScrollPane1.setViewportView(impresora);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 280, 110));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Documentos en cola:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu Documento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tipo.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        tipo.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 230, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingresa el tamaño:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingresa el tipo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 204));
        jButton3.setText("Volver");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingresa el titulo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        sel_usuario.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        sel_usuario.setForeground(new java.awt.Color(0, 153, 204));
        sel_usuario.addActionListener(this::sel_usuarioActionPerformed);
        jPanel1.add(sel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 260, -1));

        titulo.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Selecciona el Documento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        size.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        size.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Selecciona el Usuario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Documentos del Usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        doc_us.setEditable(false);
        doc_us.setColumns(20);
        doc_us.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        doc_us.setForeground(new java.awt.Color(0, 153, 204));
        doc_us.setRows(5);
        jScrollPane2.setViewportView(doc_us);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 280, 160));

        jButton4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 204));
        jButton4.setText("Eliminar Documento");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 260, -1));

        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 204));
        jButton2.setText("Ver Arbol");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (this.tipo.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar el tipo de documento");
                return;
            }
            if (this.titulo.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un titulo valido");
                return;
            }
            s.crearDocumentoParaUsuario((String) this.sel_usuario.getSelectedItem(), this.titulo.getText(), Integer.parseInt(this.size.getText()), this.tipo.getText());
            JOptionPane.showMessageDialog(rootPane, "Documento Agregado");
            this.tipo.setText("");
            this.titulo.setText("");
            this.size.setText("");
            
            this.doc_us.setText(s.obtenerDetallesTodosDocumentosUsuario((String) this.sel_usuario.getSelectedItem()));
            String[] docs = s.obtenerNombresDocumentosUsuario((String) this.sel_usuario.getSelectedItem());
            this.sel_doc.removeAllItems();
            for (String d : docs) {
                this.sel_doc.addItem(d);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Introduzca un numero para el peso");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Interfaz_Inicio i = new Interfaz_Inicio(s);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String u = (String) this.sel_usuario.getSelectedItem();
            String titulo = (String) this.sel_doc.getSelectedItem();
            
            s.eliminarDocumentoNoEncolado(u, titulo);
            
            JOptionPane.showMessageDialog(rootPane, "Documento eliminado");
            this.doc_us.setText(s.obtenerDetallesTodosDocumentosUsuario((String) this.sel_usuario.getSelectedItem()));
            String[] docs = s.obtenerNombresDocumentosUsuario((String) this.sel_usuario.getSelectedItem());
            this.sel_doc.removeAllItems();
            for (String d : docs) {
                this.sel_doc.addItem(d);
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sel_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_usuarioActionPerformed
        // TODO add your handling code here:

        this.doc_us.setText(s.obtenerDetallesTodosDocumentosUsuario((String) this.sel_usuario.getSelectedItem()));
        String[] docs = s.obtenerNombresDocumentosUsuario((String) this.sel_usuario.getSelectedItem());
        this.sel_doc.removeAllItems();
        for (String u : docs) {
            this.sel_doc.addItem(u);
        }
    }//GEN-LAST:event_sel_usuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            s.graficarColaArbol();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No hay documentos en el arbol");
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz_Documentos(s).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea doc_us;
    private javax.swing.JTextArea impresora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> sel_doc;
    private javax.swing.JComboBox<String> sel_usuario;
    private javax.swing.JTextField size;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
